from . import clinic
from . import doctor
from . import appointment
from . import patient
from . import booking
from . import medical_record
from . import examination
from . import portal_config
from . import portal_login
from . import portal_section
from . import report_portal
from . import contact
